### ISSUE TITLE
running on cpu

### ISSUE THREAD

**Issue by bashhwu** [sony/nnabla#101]
Hi, 
following the tutorial in the following link: 
http://nnabla.readthedocs.io/en/latest/python/tutorial/multi_device_training.html

I run: rc = ipp.Client(profile='mpi')
/usr/local/lib/python3.5/dist-packages/ipyparallel/client/client.py:458: RuntimeWarning: 
            Controller appears to be listening on localhost, but not on this machine.
            If this is true, you should specify Client(...,sshserver='you@bashar-ThinkPad-T460')
            or instruct your controller to listen on an external IP.
  RuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-00e242c47946>", line 1, in <module>
    rc = ipp.Client(profile='mpi')
  File "/usr/local/lib/python3.5/dist-packages/ipyparallel/client/client.py", line 511, in __init__
    self._connect(sshserver, ssh_kwargs, timeout)
  File "/usr/local/lib/python3.5/dist-packages/ipyparallel/client/client.py", line 630, in _connect
    raise error.TimeoutError("Hub connection request timed out")
ipyparallel.error.TimeoutError: Hub connection request timed out

Any idea how to solve that?

**Comment by KazukiYoshiyama** [comment]
Please look at [this url](https://ipython.org/ipython-doc/3/parallel/parallel_process.html#using-ipcluster-in-mpiexec-mpirun-mode) to turn on ipcluster in mpiexec/mpirun mode.

**Comment by TomonobuTsujikawa** [comment]
Has this already been resolved?
I will close this, but if you need further supports/questions, please recreate new issue.
