### ISSUE TITLE
running on cpu rather than GPU. dataparallel communicator  

### ISSUE THREAD

**Issue by bashhwu** [sony/nnabla#102]
in the following configuration, 
Define the communicator for gradients exchange.

%%px
extension_module = "cuda.cudnn"
ctx = extension_context(extension_module)
comm = C.MultiProcessDataParalellCommunicator(ctx)
comm.init()
n_devices = comm.size
mpi_rank = comm.rank
device_id = mpi_rank
ctx = extension_context(extension_module, device_id=device_id)

Question: what do rank and size of communicator mean?

I have tried to use CPU instead as my Graphics does not support Cuda. 

extension_module = "cpu"
ctx = extension_context(extension_module)
comm = C.DataParalellCommunicator(ctx)

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-3eb6b308b20f>", line 3, in <module>
    comm = C.DataParalellCommunicator(ctx)
  File "nnabla/communicator.pyx", line 177, in nnabla.communicator.DataParalellCommunicator (/home/gitlab-runner/builds/0cc8eecd/2/nnabla/nnabla-builder/nnabla/python/src/nnabla/communicator.cpp:2651)
RuntimeError: unclassified error in query
/home/gitlab-runner/builds/0cc8eecd/5/nnabla/nnabla-builder/nnabla/include/nbla/function_registry.hpp:77
Failed `cand.size() > 0`: ('cpu', 'default') could not be found in []

**Comment by KazukiYoshiyama** [comment]
Sorry for my belated response.

> Question: what do rank and size of communicator mean?

The size member of the communicator object is the number of processes 
you launched. For example,

When you do

```sh
$ mpirun -n 4 python ...
```

Then, `comm.size` returns 4.

The rank of the communicator is the unique index assigned to each process.

> I have tried to use CPU instead as my Graphics does not support Cuda

Currently, we do not support CPU version of a communicator, only one for CUDA device.

**Comment by TomonobuTsujikawa** [comment]
Already answered, so please let me close this.
