### ISSUE TITLE
Error when exporting model to onnx

### ISSUE THREAD

**Issue by suweijian1996** [sony/nnabla#1071]
The conversion does not support many functions, such as group normalization, is there any solution?

**Comment by suweijian1996** [comment]
Thanks for your reply, I hope some functions of onnx can be updated soon to support bigger and deeper models.

**Comment by TomonobuTsujikawa** [comment]
Sorry for taking our time.
Now, GroupNormalization is supported.

We understand many layer functions are remaining, but please let us continue to increase support status one by one.
If you have any request, please let us know. We will prioritize it.
