### ISSUE TITLE
Citation outdated

### ISSUE THREAD

**Issue by shinandrew** [sony/nnabla#1163]
Bibtex in README needs to be updated as there is a newer version of the paper.

**Comment by TomonobuTsujikawa** [comment]
Thank you for checking our paper!
Some contents seem not to be updated, so we will check it carefully.

**Comment by TomonobuTsujikawa** [comment]
It was merged by https://github.com/sony/nnabla/pull/1168
Could you please check https://github.com/sony/nnabla#citation ?

**Comment by shinandrew** [comment]
Thanks!
