### ISSUE TITLE
Header for the std::isalpha() function.

### ISSUE THREAD

**Issue by mckee-mt** [sony/nnabla#1238]
Depending on the environment, there seems to be a compilation error regarding the use of std::isalpha(). The likely cause is that the header file &lt;cctype&gt; is not included.

The target source file is _src/nbla/function/generic/einsum.cpp_.
Maybe you should add '#include &lt;cctype&gt;' to _include/nbla/common.hpp_.

K.Makiuchi

**Comment by TomonobuTsujikawa** [comment]
Thank you for valuable information.
We will add this include soon.
