### ISSUE TITLE
What is abbreviation for nnabla?

### ISSUE THREAD

**Issue by takuya-takeuchi** [sony/nnabla#124]
I'm very sorry to ask idiot question.

**Comment by carlthome** [comment]
Nabla is commonly used to denote gradients so I guess "Neural Nabla"?

**Comment by TE-andrewshin** [comment]
Sorry for a very belated reply!
Please take a look at our blog post https://blog.nnabla.org/news/the-origin-of-neural-network-libraries-repository-name-nnabla/
