### ISSUE TITLE
Tensorboard for NNabla

### ISSUE THREAD

**Issue by dganbold** [sony/nnabla#127]
Is it possible to collaborate with tensorboard ?

**Comment by andrewshinsony** [comment]
Thanks for the question. We're currently having discussion on this and will get back to you as soon as possible.

**Comment by TomonobuTsujikawa** [comment]
We prepared documents to use tensorboard. Please check it.
https://github.com/sony/nnabla/pull/774

**Comment by TomonobuTsujikawa** [comment]
I close this github issue, please submit a new one if you have any new requests and/or questions.
We hope this will be useful to you and everyone.
