### ISSUE TITLE
Reinforcement learning examples

### ISSUE THREAD

**Issue by gusdoe** [sony/nnabla#13]
Could please anybody commit to post reinforcement learning models such as DNQ and A3C? I need some hint and guide how to build reinforcement learning RNN modlez

**Comment by arita37** [comment]
You can use Mxnet and MinPY for reinforcement learning.

**Comment by takuseno** [comment]
@gusdoe Hi, if you still need some references, my repository might be helpful.
https://github.com/takuseno/nnabla-drl-collections

**Comment by gusdoe** [comment]
Thank you!

**Comment by TE-andrewshin** [comment]
You can also check out our DQN example! https://github.com/sony/nnabla-examples/tree/master/reinforcement_learning/dqn

**Comment by TomonobuTsujikawa** [comment]
I think we have already shared the information you need, so please let me close.
