### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by philipperemy** [sony/nnabla#2]
When are you going to support python 3?

Thanks

**Comment by moskomule** [comment]
Many scripts except some files, such as `setup.py` seem support both Python 2 and 3 so (I hope) Python 3 support will come sooner or later.

**Comment by HikaruIkuta** [comment]
Thanks for your feedback. We're currently working on Python 3 support, it will be available soon.

**Comment by philipperemy** [comment]
Ok thanks!

**Comment by TakuyaNarihira** [comment]
Let us leave it open to prevent another contributor open a new issue regarding this topic.

**Comment by philipperemy** [comment]
@TakuyaNarihira ok!

**Comment by kamikaze** [comment]
This is how real projects work. Python 2 is a no go for a new projects in 2017

**Comment by rafaelvalle** [comment]
@kamikaze what is a real project and why Python 2 is a no go for projects in 2017?

**Comment by kamikaze** [comment]
@rafaelvalle 
Real project is a project that has no obsolete dependencies. Python 2 is a no go because if you will start a new project in 2017 on Python 2 - it will become obsolete right after you will release it in 2020. You or your customer will have a lot of fun with it. Start thinking, guys

**Comment by philipperemy** [comment]
@rafaelvalle,

@kamikaze was referring to this: https://pythonclock.org/

**Comment by TakuyaNarihira** [comment]
Now, Python3 is supported, and can be installed by pip on almost Linux and Windows 64 bit machines. Please try it.

Commits made to support Python3: 3e9562d4fd5092f164f2a6bb6398ad29bd077073 34fda881c15d771f8bef2c7f47102e64b5c77a82

**Comment by philipperemy** [comment]
@TakuyaNarihira great job thanks!
