### ISSUE TITLE
Does nnabla C++ support BLSTM model inference now? if so, is there any docs or example? 

### ISSUE THREAD

**Issue by dengliqun** [sony/nnabla#406]
First, Thanks for the great work. 

Does nnabla C++ support BLSTM model inference now? if so, is there any docs or example?

**Comment by TE-andrewshin** [comment]
Thank you very much for your inquiry.
As of now, CPU version of LSTM is not implemented yet, but is currently in progress. We will link a pointer in this thread once it is merged.
For GPU, cuDNN version of LSTM is available, which supports bidirectional LSTM for inference. 
Please take a look at the documentation at https://nnabla.readthedocs.io/en/latest/python/api/function.html#nnabla.functions.lstm

**Comment by TomonobuTsujikawa** [comment]
Sorry for late notification.
CPU version is implemented by https://github.com/sony/nnabla/pull/596
So, please let me close this issue.
