### ISSUE TITLE
How to disable logger info output.

### ISSUE THREAD

**Issue by hotstaff** [sony/nnabla#502]
When you run the sample program in the documentation, the info log is displayed from the logger by default. 

> 2019-08-18 07:28:04,788 [nnabla][INFO]: DataSource with shuffle(True)
> 2019-08-18 07:28:04,789 [nnabla][INFO]: Using DataSourceWithMemoryCache
> 2019-08-18 07:28:04,789 [nnabla][INFO]: DataSource with shuffle(True)
> 2019-08-18 07:28:04,789 [nnabla][INFO]: On-memory
> 2019-08-18 07:28:04,789 [nnabla][INFO]: Using DataIterator

Is there a way to remove this output from the console?

**Comment by TE-AkioHayakawa** [comment]
If you would like to disable all levels of logging messages, you can do it by:
```python
from nnabla import logger
logger.disabled = True
```

Or you would like to set log level to show, you can do it by:
```python
from nnabla import logger
import logging
logger.setLevel(logging.ERROR) #  you can set any log levels you want.
```
Please see https://docs.python.org/3/howto/logging.html to get more detail information about `logging` package.

**Comment by hotstaff** [comment]
My problem has been solved. I knew how to use python logging, but I didn't know how to configure nnabla's logger module. Thank you very much. It seemed very easy, but finding a solution was difficult. Thank you very much.
