### ISSUE TITLE
nnabla_utils link errors.

### ISSUE THREAD

**Issue by skinner-repository** [sony/nnabla#712]
I found nnabla_utils link errors caused by GNUmakefiles in nnabla/examples/cpp/, and fix them.
We should add "-lnnabla_utils" to all compile command lines in GNUmakefiles accurately.
1. nnabla/examples/cpp/mnist_collection/GNUmakefile
    add " -lnnabla_utils" to all compile command lines.
2. nnabla/examples/cpp/mnist_runtime/GNUmakefile
    collect " -lnbla_utils" to "-lnnabla_utils"
3. nnabla/examples/cpp/mnist_training/GNUmakefile
    collect " -lnbla_utils" to "-lnnabla_utils"

**Comment by TomonobuTsujikawa** [comment]
Thank you, this issue has already been corrected, so close this ticket.
