### ISSUE TITLE
OSX Version

### ISSUE THREAD

**Issue by dataf3l** [sony/nnabla#737]
Hi guys, I'm a fan of your work, it looks very exciting.
However, I wonder if this project plans to support mac osx.
if this is not planned, I'd like to know how can I help this mac version.

A lot of people use linux and mac on academia.

Are there plans for a portable ui?

**Comment by TomonobuTsujikawa** [comment]
Hi, thank you for your question.
We have been releasing nnabla packages for Intel Mac.
https://pypi.org/project/nnabla/#files

Regarding to graphical user interface, we're sorry but nothing works on Mac at this time.

**Comment by TomonobuTsujikawa** [comment]
I close this issue.
If you have additional request, please create new github issue.
