### ISSUE TITLE
nnabla-ext-cuda102 with cuDNN 7.6

### ISSUE THREAD

**Issue by JeffreyCA** [sony/nnabla#770]
Is it possible to maintain a version of nnabla-ext-cuda102 for both cuDNN 7.6 and 8.0 (Linux + Windows)?
As of the latest version, it looks like only the Windows version is for 7.6 and on Linux it's 8.0.

**Comment by TomonobuTsujikawa** [comment]
In our current plan, we will support the following environments (not only Linux but also Windows).
* CUDA 10.0 x cuDNN 7.6
* CUDA 10.2 x cuDNN 8.0
* CUDA 11.0 x cuDNN 8.0

We currently provide CUDNN7.6 packages for Windows CUDA10.2 environment as you pointed, but will shift to CUDNN8 in the near future.

**Comment by TomonobuTsujikawa** [comment]
I close this issue.
We still support CUDA10.2 x cudNN 7 on Windows as of now, but we would like to shift to cudNN8 as soon as possible.
Also, if you need pypi deprecated packages, you can install them from https://nnabla.org/install/.

If you have additional request, please create a new github issue.
