### ISSUE TITLE
value error in nnabla on running x-umx on Rpi4, Raspberry Pi OS

### ISSUE THREAD

**Issue by RajivX** [sony/nnabla#786]
On running x-umx on Rpi4, 8GB on Raspberry Pi OS i get the below error,

root@raspberrypi:/home/pi/x-umx# python3 test.py  --inputs ../Music/test_16k_S16_LE_stereo.wav --context cpu --model /home/pi/x-umx/x-umx.h5 --outdir /home/pi/x-umx/results
2021-01-30 16:37:37,007 [nnabla][INFO]: Initializing CPU extension...
Traceback (most recent call last):
  File "test.py", line 198, in <module>
    test()
  File "test.py", line 170, in test
    residual_model=args.residual_model
  File "test.py", line 84, in separate
    mix_spec, msk, _ = unmix_target(audio_nn, test=True)
  File "/home/pi/x-umx/model.py", line 300, in __call__
    lstm_out_bass = self.lstm(cross_1, nb_samples, "lstm_bass", test)
  File "/home/pi/x-umx/model.py", line 231, in lstm
    bidirectional=not self.unidirectional, training=not test, dropout=0.4, name=scope_name)
  File "<string>", line 8, in lstm
  File "/usr/local/lib/python3.7/dist-packages/nnabla/parametric_functions.py", line 1567, in lstm
    return F.lstm(x, h, c, weight_l0=w0, weight=w, bias=b, num_layers=num_layers, dropout=dropout, bidirectional=bidirectional, training=training)
  File "<lstm>", line 3, in lstm
  File "/usr/local/lib/python3.7/dist-packages/nnabla/function_bases.py", line 222, in lstm
    return F.LSTM(ctx, num_layers, dropout, bidirectional, training)(*inputs, n_outputs=n_outputs, auto_forward=get_auto_forward(), outputs=outputs)
  File "function.pyx", line 292, in nnabla.function.Function.__call__
  File "function.pyx", line 271, in nnabla.function.Function._cg_call
RuntimeError: value error in setup_impl
/home/pi/x-umx/nnabla/src/nbla/function/./generic/split.cpp:36
Failed `num_outputs_ == outputs.size()`: inputs[0].shape[axis] must be the same number as the outputs. inputs[0].shape[axis]: 431, outputs: 2.

I have successfully manually built & installed nnabla & llvmlite. 
The latter was really very difficult to build & install.
root@raspberrypi:/home/pi/x-umx# pip3 freeze | grep 'nnabla'
nnabla==1.9.0
root@raspberrypi:/home/pi/x-umx# pip3 freeze | grep 'llvmlite'
llvmlite==0.32.1+0.gaa11b12.dirty

I think, now it is throwing error related to nnabla, of the input parameter size not equivalent to
output parameter size. Can you please suggest, where we need to set this nnabla files ?

Please help me.
Regards,
Rajiv.

**Comment by RajivX** [comment]
Yes, i could solve it successfully. I installed the latest version of nnabla, ver 1.17 as of today,
root@raspberrypi:/home/pi/x-umx/results# pip3 freeze | grep 'nnabla'
nnabla==1.17.0.dev1

This version solves the issue. Please close the ticket.

**Comment by TomonobuTsujikawa** [comment]
Thank you for running x-umx on Rpi4 environment!
I close this issue, and we would like to support Rasberry Pi environment in the near future!
