### ISSUE TITLE
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by cravisjan97** [sony/nnabla#806]
I installed nnabla using ```pip install nnabla-ext-cuda102``` and I have CUDA-10.2 installed on my system. I have also added 
```export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64:$LD_LIBRARY_PATH``` 
```export PATH=/usr/local/cuda-10.2/bin${PATH:+:${PATH}}``` in my .bashrc file. I am not able to solve this error. I am able to use nnabla with CPU extension though.

**Comment by TomonobuTsujikawa** [comment]
Hi,
To run nnabla with GPU, you need to install CUDA and cudNN.
Please refer this nvidia installation page to install cudnn: https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html
You need to join free nvidia developer program to download cudnn.

If you already installed cudnn8, please add the directory path to LD_LIBRARY_PATH.

**Comment by TomonobuTsujikawa** [comment]
Please let me close this issue.
If you still face this problem, please create new ticket with error messages.
