### ISSUE TITLE
c++ project unable to execute the program due to DLL reference error

### ISSUE THREAD

**Issue by CrimsonTuna** [sony/nnabla#847]
https://github.com/sony/nnabla/blob/master/doc/build/build_cpp_utils_windows.md

I have created a c++ project referring to the above document. (using VisualStudio 2019, Windows 10) 
However, when I execute the program, it throws exceptions because cannot find the following DLLs.

1. liiblz4.dll
2. zstd.dll

How can i fix it?

**Comment by TomonobuTsujikawa** [comment]
Sorry, we found same issue, and fixed it by https://github.com/sony/nnabla/pull/848.
This PR has many changes, but we added 2 batch files (get_liblz4.bat and get_libzstd.bat) to resolve this issue.

So, please rebuild your project with latest nnabla code.
I hope you can fix this issue.

**Comment by TomonobuTsujikawa** [comment]
nnabla v1.19.0 was released.
Please see the spotlights and changes: https://blog.nnabla.org/release/v1-19-0/

We think this issue was resolved, so please let me close this issue.
If you haven't solved yet, please create new one.
