### ISSUE TITLE
TFLite converter needs `flatc` command.

### ISSUE THREAD

**Issue by YukioOobuchi** [sony/nnabla#898]
The conversion to TFLite format has been greatly improved in nnabla 1.20.0, but since the `flatc` command is used internally, the conversion will fail if the `flatc` command is not installed in the environment used beforehand.

We plan to make further improvements to make it easier to use, but as of now you can either build it yourself using https://google.github.io/flatbuffers/flatbuffers_guide_building.html as a guide or install the flatc command in `snap install flatbuffers` under Linux environment.

**Comment by TomonobuTsujikawa** [comment]
flatc is now included in nnabla-converter wheel from v1.30.0.
https://github.com/sony/nnabla/pull/1084

So, you don't need to install flatc by yourself.
