### ISSUE TITLE
ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mmnn-nnmm** [sony/nnabla#914]
Hello,
My system already has CUDA(v8.0.61) and cuDNN installed.
So I installed nnabla and CUDA extension package using pip as below:
`pip install nnabla`
`pip install nnabla-ext-cuda80`

I have also added
`export PATH="/usr/local/cuda-8.0/bin:$PATH"`
`export LD_LIBRARY_PATH="/usr/local/cuda-8.0/lib64:$LD_LIBRARY_PATH"`
in .bashrc file.

Then, check nnabla by running:
`python -c "import nnabla"`
`2021-07-08 11:*:*,854 [nnabla][INFO]: Initializing CPU extension...`
But when I check nnabla_ext, I got an error message.
`python -c "import nnabla_ext.cuda, nnabla_ext.cudnn"`
`ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory`

By the way, I confirmed "/usr/local/cuda-8.0/lib64/",  I could find only "libcudnn.so.6".

**Comment by TomonobuTsujikawa** [comment]
Thank you for using nnabla!

Your system cannot find correct cudnn libraries which is used by nnabla-ext-cuda80.
So, if you didn't install cudnn7, please install cudnn7 at first, then setup ldconfig or LD_LIBRARAY_PATH.

But, nnabla currently supports cuda10.0/cudnn7, 10.2/cudnn8 and 11.0/cudnn8.
So, if you can update your system, we recommend to use cuda10 or cuda11.
You can find how to install cuda/cudnn and nnabla from https://nnabla.org/install/

**Comment by TomonobuTsujikawa** [comment]
Please let me close this issue.
And please let us know if you still can't run nnabla correctly, we will support you what you want to do as much as possible.
