### ISSUE TITLE
Model Parallelism Support

### ISSUE THREAD

**Issue by MiZhangWhuer** [sony/nnabla#916]
Great work! Is there any plan for model parallelism? Looking forward to the demo.

**Comment by TomonobuTsujikawa** [comment]
Thank you for checking nnabla!
As of now, we have no concrete plan to support model parallelism as platform.

But, nnabla overcomes GPU memory limitations by OoC (Out of Core) and re-computation features.
Now, please try to train your model with them.

**Comment by MiZhangWhuer** [comment]
> Thank you for checking nnabla!
> As of now, we have no concrete plan to support model parallelism as platform.
> 
> But, nnabla overcomes GPU memory limitations by OoC (Out of Core) and re-computation features.
> Now, please try to train your model with them.

Thanks for the comments. Could you please provide the details on OoC and re-computation? Is there any material and implementation instruction on it?

**Comment by TomonobuTsujikawa** [comment]
Thank you for checking.
we may need to write more document, but please check the following release blogs:
Recompute : https://blog.nnabla.org/release/v1-20-0/
OoC : https://blog.nnabla.org/release/v1-16-0/

**Comment by TomonobuTsujikawa** [comment]
Please let me close this. If you have any questions, please open new issues.
