### ISSUE TITLE
How does visit_function_recursive works?

### ISSUE THREAD

**Issue by MiZhangWhuer** [sony/nnabla#927]
Hi, I notice that there exists a function called "visit_function_recursive". How does it work? It is served as the the DAG construction from the output to it's root recursively?  Is the depth first search (DFS) utilized as the default algorithm? 

https://github.com/sony/nnabla/blob/ed840be7f76b283fec04902744e23a18d293de04/src/nbla/computation_graph/variable.cpp#L640

**Comment by TomonobuTsujikawa** [comment]
>How does it work? It is served as the the DAG construction from the output to it's root recursively?

Yes, the recursive traverse is performed from output to its input.
This function performs a recursive function traverse, along computation graph topologies, from leaves(outputs) to its root(inputs). But the sequence call `forward_callback` is exactly as the sequence when perform an inferring operation.
 
>Is the depth first search (DFS) utilized as the default algorithm?

Almost it is. But as above, the `forward_callback` is called with the sequence exactly as the computation graph is inferred, for input to output.

**Comment by TomonobuTsujikawa** [comment]
I think your concern have solved, so please let me close this.
If you feel unclear or have additional questions, please submit new issue!
