### ISSUE TITLE
Error in running: mpirun -n 4 python  multi_device_multi_process_classification.py

### ISSUE THREAD

**Issue by MiZhangWhuer** [sony/nnabla#946]
When running multi-gpu support as suggested, the following error occurs:

comm = C.MultiProcessDataParalellCommunicator(ctx)
File "communicator.pyx", line 653, in nnabla.communicator.MultiProcessDataParallelCommunicator
RuntimeError: value error in query
Failed `it != items_.end()`: Any of [cudnn:float, cuda:float, cpu:float] could not be found in []

How to fix it?

**Comment by MiZhangWhuer** [comment]
solved with CMake flag -D WITH_NCCL=ON. Close it.

**Comment by FarisHijazi** [comment]
I'm getting the same error when running using `mpirun` and my installation is from `pip install nnabla-ext-cuda110`

python3.6

Is rebuilding it the only way? and are there docs for building nnabla?

**Comment by TomonobuTsujikawa** [comment]
We have prepared other packages.
When you try to run distributed training, please install one of the following pip packages:
(Please refer to https://nnabla.org/install for preparing environment)
* nnabla-ext-cuda110-nccl2-mpi3-1-6 (for mpi3.1.6 environment)
* nnabla-ext-cuda110-nccl2-mpi2-1-1 (for mpi2.1.1 environment)

As another solution, we have provided docker images for each version of python/cuda.
Please try these images:
* nnabla/nnabla-ext-cuda-multi-gpu:py36-cuda110-mpi3.1.6-v1.21.0
* nnabla/nnabla-ext-cuda-multi-gpu:py36-cuda110-mpi2.1.1-v1.21.0

This will be able to run:
```bash
docker run --gpus all --rm -it -v $(pwd)/nnabla-examples:/opt2 nnabla/nnabla-ext-cuda-multi-gpu:py36-cuda110-mpi3.1.6-v1.21.0 /bin/bash
mpirun -n 4 python /opt2/distributed/cifar10-100/multi_device_multi_process_classification.py
```

**Comment by TomonobuTsujikawa** [comment]
We're sorry for taking up your precious time, but we're happy it works properly!

Yes, your opinion is completely right. We would like to prepare some descriptions to our installation page.
