### ISSUE TITLE
The role of parametric variable pv plays?

### ISSUE THREAD

**Issue by MiZhangWhuer** [sony/nnabla#959]
In the graph_def.py, there exists a local variable pv:
https://github.com/sony/nnabla/blob/7a1a7131c148fdc3477e1e7124898f0fce07bbc5/python/src/nnabla/core/graph_def.py#L843

It seems that the pv has no effect on the from_proto function. Can we remove it in the from_proto function?

**Comment by TomonobuTsujikawa** [comment]
Thank you for your code review.

pv is useful here.
pv is the reference of g.variable[v.name] or g.parameters[v.name], Here, we use abbreviation pv to refer to one of them so that the code looks readable, avoid to duplicated g.variable[xxx].
So, you cannot remove pv from this scope.

Thanks!

**Comment by TomonobuTsujikawa** [comment]
I hope you got why pv is used in this sentence, so please let me close this.
If you feel unclear or have additional questions, please create new issue.
