### ISSUE TITLE
GPU compatibility could not be verified due to a problem getting the GPU list

### ISSUE THREAD

**Issue by Charlottecuc** [sony/nnabla#991]
```
pip install nnabla-ext-cuda102
python3 -c "import nnabla_ext.cuda, nnabla_ext.cudnn"
2021-11-25 11:18:30,707 [nnabla][INFO]: Initializing CPU extension...
GPU compatibility could not be verified due to a problem getting the GPU list.
2021-11-25 11:18:32,740 [nnabla][INFO]: Initializing CUDA extension...
2021-11-25 11:18:32,937 [nnabla][INFO]: Initializing cuDNN extension...
```

Cuda version: 10.2

**Comment by Charlottecuc** [comment]
```
CUDNN_VERSION 8.1.1
GPU: Tesla T4
```
Do you know how to solve this problem? Thank you very much

**Comment by TomonobuTsujikawa** [comment]
It seems to fail nvml initialization.
We will use libnvidia-ml.so.1 for Linux, or nvml.dll for Windows.
We expect nvml.dll to be in `C:\Windows\System32` or `C:\Program Files\NVIDIA Corporation\NVSMI`.

If you have the library in another directory, it will be run by copying it to above directory (Windows) or setting LD_LIBRARY_PATH (Linux).
If you don't find the library, you can install it by cuda-drivers.
Please check https://nnabla.org/install/ how to setup environment.
